
export default {
  loading: false,
  dashboards: [],
  slices: [],
  datasources: [],
  sliceTree: {},
  users: [],
  user: {},
  dimensions: [],
  measures: [],
  measure: {},
  dimension: {},
  datasource: {},
  roles: [],
  permissions: [],
  subscribes: [],
  usergroups: [],
  originDimensions: [],
  originMeasures: [],
  tags: [],
  pioProjects: [],
  operators: [],
  segmentExpands: [],
  projects: [],
  lossPredicts: [],
  pathAnalysis: [],
  pioCases: [],
  monitors: [],
  monitorAlarms: [],
  companys: [],
  tagTypes: [],
  tagGroups: [],
  tagTrees: [],
  dashboardsCategory: []
}
